apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    service: api  
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 3456
    protocol: TCP
    targetPort: 3456
  selector:
    service: api
    release: {{ .Release.Name }}
