apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    service: frontend
    release: {{ .Release.Name }} 
spec:
  {{- if .Values.frontend.replicas }}
  replicas: {{ .Values.frontend.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      service: frontend
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        service: frontend
    spec:
      automountServiceAccountToken: true
      containers:
      - name: {{ .Release.Name }}-frontend
        image: "{{ .Values.image.repository }}/frontend:{{ .Values.frontend.imagetag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: VIKUNJA_API_URL
          value: "{{ .Values.env.VIKUNJA_API_URL }}"
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1

