apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    service: keycloak
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: keycloak
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        service: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:20.0.3
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "{{ .Values.env.VIKUNJA_KEYCLOAK_ADMIN }}"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "{{ .Values.env.VIKUNJA_KEYCLOAK_PASS }}"
        - name: DB_ADDR
          value: "{{ .Values.env.VIKUNJA_DATABASE_HOST }}"
        - name: DB_USERNAME
          value: "{{ .Values.env.VIKUNJA_DATABASE_USER }}"
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgres-password
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "keycloakdemo"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
