apiVersion: v1
kind: Service
metadata:
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/name: api  
    app.kubernetes.io/service: {{ .Release.Name }}-api 
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 3456
    protocol: TCP
    targetPort: 3456
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: api
    release: {{ .Release.Name }}
