name: Deploy Helm Chart

on:
  push:
    branches:
      - main  # Trigger on main branch commits

  deploy-vikunja:
    name: Deploy Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

     - name: Update KubeConfig 
       run: |   
         aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region=${{ env.AWS_REGION }}
     
      - name: Deploy Helm Chart To Amazon EKS Cluster
        env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          helm install ${{ env.HELM_CHART_NAME }} eks/helm/ --set containers.image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  
